name: CI
on: 
  push: 
    branches:
      main
jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.head_ref }}
          
      - uses: actions/setup-node@v3
        with:
          node-version: 18
      
      - name: Installing prettier
        run: npm i
      - name: formatting
        run: npx prettier --write .
    
      - name: push changes
        run: |
          if [ ! -z "$(git status --porcelain)" ]; then
            git config --global user.name "PrettierFormatter"
            git config --global user.email "username@users.noreply.github.com"
            git commit -a -m "Apply prettier formatted code"
            git push
          fi
